IntranetSite/ViewModels/DetailsConteudoPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using IntranetAssemblies.Models.Intranet;

namespace IntranetSite.ViewModels
{
    public class DetailsConteudoPartialViewModel
    {
        public Conteudo Conteudo { get; set; }
        public List<ConteudoAnexo> ConteudoAnexosList { get; set; }
        public List<string> Fotos { get; set; }
        public List<Link> Links { get; set; }
        public ConteudoPropriedade ConteudoEstado { get; set; }
        public ConteudoPropriedade ConteudoVisibilidade { get; set; }

        public Ficha_Curso Ficha_Curso_Dados { get; set; }

        public DetailsConteudoPartialViewModel()
        {
            Conteudo = new Conteudo();
            ConteudoAnexosList = new List<ConteudoAnexo>();
            ConteudoEstado = new ConteudoPropriedade();
            ConteudoVisibilidade = new ConteudoPropriedade();
            Fotos = new List<string>();
            Links = new List<Link>();
            Ficha_Curso_Dados = new Ficha_Curso();
        }
    }
}

IntranetSite/Controllers/FormGenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;

using IntranetSite.App_Start;
using IntranetSite.Filters;
using IntranetSite.ViewModels;

using IntranetAssemblies.Models.Intranet;
using IntranetSite.Clients;
using IntranetAssemblies.Models.QuoVadis.Cargos;

namespace IntranetSite.Controllers
{
    public class FormGenController : ConteudosFormsController
    {
        private readonly CargosClient _cargosClient = new CargosClient();

        public ActionResult LoadDetailsConteudoPartial(int id)
        {
            DetailsConteudoPartialViewModel detailsConteudoPartialViewModel = new DetailsConteudoPartialViewModel();

            detailsConteudoPartialViewModel.Conteudo = _intranetService.STP_Conteudos_S(id);

            if (detailsConteudoPartialViewModel.Conteudo != null && detailsConteudoPartialViewModel.Conteudo.Id > 0)
            {
                detailsConteudoPartialViewModel.ConteudoAnexosList = _intranetService.STP_ConteudosAnexos_S_ByConteudo(id);
                detailsConteudoPartialViewModel.ConteudoEstado = GetConteudoEstado(detailsConteudoPartialViewModel.Conteudo.Estado);
                detailsConteudoPartialViewModel.ConteudoVisibilidade = GetConteudoVisibilidade(detailsConteudoPartialViewModel.Conteudo.VisibilidadePublica);
            }

            return PartialView("DetailsConteudoPartial", detailsConteudoPartialViewModel);
        }

        [IntranetLoggedIn]
        public ActionResult CreateConteudo(int idTipoConteudo, int idOrgao)
        {
            // Antes de tudo, limpa da sessão do browser quaisquer dados de conteúdos antigos que foram criados/editados
            IntranetSession.ClearConteudoSession();

            CreateEditConteudoViewModel createConteudoViewModel = new CreateEditConteudoViewModel();

            // Obtém, a partir dos respectivos ID's, todos os dados do tipo de conteúdo e do órgão do novo conteúdo
            TipoConteudo tipoConteudo = _cargosClient.GetTipoConteudo(idTipoConteudo);

            // Associa logo ao novo conteúdo os IDs do tipo de conteúdo e da unidade orgânica seleccionados
            createConteudoViewModel.Conteudo.IdTipoConteudo = idTipoConteudo;
            createConteudoViewModel.Conteudo.IdOrgao = idOrgao;
            createConteudoViewModel.Conteudo.NomeTipoConteudo = tipoConteudo.Nome;

            //Define a data de inicio de publicação por defeito para hoje
            createConteudoViewModel.Conteudo.DataInicioPublicacao = DateTime.Now;

            //Preencher as labels que são necessárias preencher no formulário
            createConteudoViewModel.Conteudo.LabelData1 = "Data do Documento";

            RefreshCreateEditConteudoViewModel(createConteudoViewModel);

            return View(createConteudoViewModel);
        }

        [HttpPost]
        [IntranetLoggedIn]
        public ActionResult CreateConteudo(CreateEditConteudoViewModel createConteudoViewModel)
        {
            if (string.IsNullOrEmpty(createConteudoViewModel.Conteudo.Titulo) == true)
            {
                ModelState.AddModelError("Conteudo.Titulo", "Tem de preencher este campo!");
            }

            if (createConteudoViewModel.Conteudo.DataInicioPublicacao == null || createConteudoViewModel.Conteudo.DataInicioPublicacao == new DateTime())
            {
                ModelState.AddModelError("Conteudo.DataInicioPublicacao", "Tem de preencher este campo!");
            }

            //if (createConteudoViewModel.Conteudo.DataFimPublicacao == null || createConteudoViewModel.Conteudo.DataFimPublicacao == new DateTime())
            //{
            //    ModelState.AddModelError("Conteudo.DataFimPublicacao", "Tem de preencher este campo!");
            //}

            //if (createConteudoViewModel.Conteudo.DataFimPublicacao < createConteudoViewModel.Conteudo.DataInicioPublicacao)
            //{
            //    ModelState.AddModelError("Conteudo.DataFimPublicacao", "A data de fim de publicação tem de ser superior à de início");
            //}
            if (createConteudoViewModel.Conteudo.DataFimPublicacao != null && createConteudoViewModel.Conteudo.DataFimPublicacao != new DateTime())
            {
                if (createConteudoViewModel.Conteudo.DataFimPublicacao < createConteudoViewModel.Conteudo.DataInicioPublicacao)
                {
                    ModelState.AddModelError("Conteudo.DataFimPublicacao", "A data de fim de publicação tem de ser superior à de início");
                }
            }

            if (IntranetSession.Session.ConteudoAnexosFiles.Where(caf => caf.WasDeletedByUser == false).Count() < 1)
            {
                ModelState.AddModelError("ConteudoAnexoFile", "Tem de escolher no mínimo um ficheiro!");
            }

            if (ModelState.IsValid == true)
            {
                int? id = CreateConteudo(createConteudoViewModel.Conteudo);

                if (id != null && id > 0)
                {
                    TempData["success"] = "Dados submetidos com êxito!";

                    return RedirectToAction("EditConteudo", new { id = id });
                }
                else
                {
                    TempData["error"] = "Ocorreu um erro ao submeter dados!";
                }
            }
            else
            {
                TempData["error"] = "Dados não válidos! Por favor verifique todos os campos e tente de novo.";
            }

            RefreshCreateEditConteudoViewModel(createConteudoViewModel);

            return View(createConteudoViewModel);
        }

        [IntranetLoggedIn]
        public ActionResult EditConteudo(int id)
        {
            // Antes de tudo, limpa da sessão do browser quaisquer dados de conteúdos antigos que foram criados/editados
            IntranetSession.ClearConteudoSession();

            CreateEditConteudoViewModel editConteudoViewModel = new CreateEditConteudoViewModel();

            editConteudoViewModel.Conteudo = _intranetService.STP_Conteudos_S(id);

            if (editConteudoViewModel.Conteudo != null && editConteudoViewModel.Conteudo.Id > 0)
            {
                RefreshCreateEditConteudoViewModel(editConteudoViewModel);

                // Com os dados do conteúdo obtidos, passa para a obtenção dos dados dos anexos do conteúdo
                List<ConteudoAnexo> conteudoAnexosList = _intranetService.STP_ConteudosAnexos_S_ByConteudo(id);

                if (conteudoAnexosList != null && conteudoAnexosList.Count > 0)
                {
                    try
                    {
                        // Através dos dados do conteúdo, obtém o caminho da pasta onde os ficheiros dos anexos se encontram
                        Parametro intranetFolderPath = _intranetService.NSI_STP_Parametros_S_ByChave("Aplicacao.FolderPath");

                        string conteudoAnexosFilesFolderPath = intranetFolderPath.Valor + editConteudoViewModel.Conteudo.CodigoOrgao + "-" + editConteudoViewModel.Conteudo.DataCriacao.Year + "-" + editConteudoViewModel.Conteudo.DataCriacao.Month + "-" + editConteudoViewModel.Conteudo.DataCriacao.Day;

                        // Verifica se a pasta correspondente ao caminho anteriormente obtido existe
                        if (Directory.Exists(conteudoAnexosFilesFolderPath) == true)
                        {
                            foreach (ConteudoAnexo conteudoAnexo in conteudoAnexosList)
                            {
                                // Verifica se o ficheiro correspondente ao anexo do conteúdo existe
                                if (System.IO.File.Exists(conteudoAnexosFilesFolderPath + @"\" + conteudoAnexo.Anexo) == true)
                                {
                                    // Se o ficheiro existir, guarda os dados do ficheiro na sessão do browser
                                    // Na view, o plugin Dropzone.JS vai ler estes dados para apresentar os ficheiros que se encontram anexados ao conteúdo
                                    ConteudoAnexoFile conteudoAnexoFile = new ConteudoAnexoFile();

                                    FileInfo conteudoAnexoFileInfo = new FileInfo(conteudoAnexosFilesFolderPath + @"\" + conteudoAnexo.Anexo);

                                    conteudoAnexoFile.Id = conteudoAnexo.Id;
                                    conteudoAnexoFile.Name = conteudoAnexo.Anexo;
                                    conteudoAnexoFile.Size = conteudoAnexoFileInfo.Length;

                                    IntranetSession.Session.ConteudoAnexosFiles.Add(conteudoAnexoFile);
                                }
                            }
                        }
                    }
                    catch (Exception e)
                    {
                        // TO DO: Fazer log de quaisquer excepções que ocorram
                    }
                }
            }

            return View(editConteudoViewModel);
        }

        [HttpPost]
        [IntranetLoggedIn]
        public ActionResult EditConteudo(int id, CreateEditConteudoViewModel editConteudoViewModel)
        {
            if (string.IsNullOrEmpty(editConteudoViewModel.Conteudo.Titulo) == true)
            {
                ModelState.AddModelError("Conteudo.Titulo", "Tem de preencher este campo!");
            }

            if (editConteudoViewModel.Conteudo.DataInicioPublicacao == null || editConteudoViewModel.Conteudo.DataInicioPublicacao == new DateTime())
            {
                ModelState.AddModelError("Conteudo.DataInicioPublicacao", "Tem de preencher este campo!");
            }

            if (editConteudoViewModel.Conteudo.DataFimPublicacao == null || editConteudoViewModel.Conteudo.DataFimPublicacao == new DateTime())
            {
                ModelState.AddModelError("Conteudo.DataFimPublicacao", "Tem de preencher este campo!");
            }

IntranetSite/Views/FormGen/CreateConteudo.cshtml
@model IntranetSite.ViewModels.CreateEditConteudoViewModel

@{
    ViewBag.Title = "Novo Conteúdo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("CreateConteudo", "FormGen", FormMethod.Post, new { @id = "form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12">
            <div class="form-horizontal">
                <h4>@Model.Conteudo.NomeTipoConteudo</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Conteudo.IsForEstudante)
                @Html.HiddenFor(model => model.Conteudo.IdTipoConteudo)
                @Html.HiddenFor(model => model.Conteudo.IdOrgao)
                @Html.HiddenFor(model => model.Conteudo.NomeTipoConteudo)
                @Html.HiddenFor(model => model.Conteudo.LabelData1)

                <div class="form-group">
                    @Html.LabelFor(model => model.Conteudo.Titulo, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Titulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Conteudo.Descricao, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Conteudo.DataInicioPublicacao, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Conteudo.DataInicioPublicacao, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Conteudo.DataInicioPublicacao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Conteudo.DataFimPublicacao, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Conteudo.DataFimPublicacao, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Conteudo.DataFimPublicacao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("model.Conteudo.LabelData1", Model.Conteudo.LabelData1, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Data1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Data1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Ficheiros em anexo", htmlAttributes: new { @class = "control-label col-md-12" })
                    <div id="actions" class="col-md-12">
                        <span class="btn btn-block btn-success fileinput-button dz-clickable">
                            <span class="fa fa-file"></span>
                            Escolher Ficheiro
                        </span>
                        @Html.ValidationMessage("ConteudoAnexoFile", "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <div class="table table-striped" id="previews">

                            </div>
                        </div>

                        <div id="tpl">
                            <div id="template" class="file-row">
                                <div>
                                    <p class="name" data-dz-name></p>
                                    <strong class="error text-danger" data-dz-errormessage></strong>
                                </div>
                                <div>
                                    <p class="size" data-dz-size></p>
                                </div>
                                <div class="text-right">
                                    <button type="button" data-dz-remove class="btn btn-warning remove">
                                        <span class="fa fa-times"></span>
                                        Remover
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-horizontal">
                <hr />

                <div class="form-group">
                    <div class="col-md-12">
                        <a class="btn btn-danger" href="@Url.Action("CreateConteudos", "Conteudos")">
                            <span class="fa fa-times"></span>
                            Cancelar
                        </a>
                        <button type="submit" class="btn btn-primary">
                            <span class="fa fa-plus"></span>
                            Criar Conteúdo
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        var previewWrapper = document.querySelector("#tpl");
        previewWrapper.id = "";
        var previewTemplate = previewWrapper.innerHTML;
        previewWrapper.remove();

        var myDropzone = new Dropzone(document.getElementById("form"), {
            url: "@Url.Action("CreateConteudoAnexoFiles")",
            paramName: "files",
            maxFiles: 10,
            maxFilesize: 100,
            timeout: 0,
            uploadMultiple: true,
            previewTemplate: previewTemplate,
            previewsContainer: "#previews",
            createImageThumbnails: false,
            clickable: ".fileinput-button",

            dictFileTooBig: "O tamanho deste ficheiro é demasiado grande! O tamanho máximo suportado é {{maxFilesize}}.",
            dictResponseError: "Ocorreu um erro ao submeter este ficheiro (Erro {{statusCode}})!",
            dictMaxFilesExceeded: "Só pode escolher no máximo 10 ficheiro!",

            init: function() {
                let myDropzone = this;

                myDropzone.on("success", function (file) {
                    file.previewElement.querySelector(".remove").onclick = function () {
                        $.post("@Url.Action("DeleteConteudoAnexoFile")", { conteudoAnexoFileName: file.name }, function () {
                            if (file.isMockFile == true) {
                                myDropzone.options.maxFiles = myDropzone.options.maxFiles + 1;
                            }
                        });
                    }
                });

                $.get("@Url.Action("GetConteudoAnexoFiles")", function (data) {
                    data.forEach(function (file) {
                        let mockFile = { name: file.Name, size: file.Size, isMockFile: true };

                        myDropzone.files.push(mockFile);

                        myDropzone.emit("addedfile", mockFile);
                        myDropzone.emit("complete", mockFile);
                        myDropzone.emit("success", mockFile);

                        myDropzone.options.maxFiles = myDropzone.options.maxFiles - 1;
                    });
                });
            }
        });

       
    });
</script>

IntranetSite/Views/FormGen/EditConteudo.cshtml
@model IntranetSite.ViewModels.CreateEditConteudoViewModel

@{
    ViewBag.Title = "Editar Conteúdo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditConteudo", "FormGen", FormMethod.Post, new { @id = "form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-9">
            <div class="form-horizontal">
                <h4>@Model.Conteudo.NomeTipoConteudo</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Conteudo.Id)
                @Html.HiddenFor(model => model.Conteudo.IUPI)
                @Html.HiddenFor(model => model.Conteudo.IsForEstudante)
                @Html.HiddenFor(model => model.Conteudo.DataCriacao)
                @Html.HiddenFor(model => model.Conteudo.CodigoOrgao)
                @Html.HiddenFor(model => model.Conteudo.NomeTipoConteudo)
                @Html.HiddenFor(model => model.Conteudo.LabelData1)


                <div class="form-group">
                    @Html.LabelFor(model => model.Conteudo.Titulo, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Titulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Conteudo.Descricao, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Conteudo.DataInicioPublicacao, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Conteudo.DataInicioPublicacao, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Conteudo.DataInicioPublicacao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Conteudo.DataFimPublicacao, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Conteudo.DataFimPublicacao, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Conteudo.DataFimPublicacao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("model.Conteudo.LabelData1", Model.Conteudo.LabelData1, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Conteudo.Data1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conteudo.Data1, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.Label("Ficheiros em anexo", htmlAttributes: new { @class = "control-label col-md-12" })
                    <div id="actions" class="col-md-12">
                        <span class="btn btn-block btn-success fileinput-button dz-clickable">
                            <span class="fa fa-file"></span>
                            Escolher Ficheiro
                        </span>
                        @Html.ValidationMessage("ConteudoAnexoFile", "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <div class="table table-striped" id="previews">

                            </div>
                        </div>

                        <div id="tpl">
                            <div id="template" class="file-row">
                                <div>
                                    <p class="name" data-dz-name></p>
                                    <strong class="error text-danger" data-dz-errormessage></strong>
                                </div>
                                <div>
                                    <p class="size" data-dz-size></p>
                                </div>
                                <div class="text-right">
                                    <button type="button" data-dz-remove class="btn btn-warning remove">
                                        <span class="fa fa-times"></span>
                                        Remover
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <div class="form-horizontal">
                <hr />

                <div class="form-group">
                    <div class="col-md-12">
                        <a class="btn btn-danger" href="@Url.Action("EditConteudos", "Conteudos")">
                            <span class="fa fa-times"></span>
                            Cancelar
                        </a>
                        <button type="submit" class="btn btn-primary">
                            <span class="fa fa-plus"></span>
                            Gravar Conteúdo
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            @{
                Html.RenderPartial("CreateEditConteudoPropriedadesPartial", Model);
            }
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        var previewWrapper = document.querySelector("#tpl");
        previewWrapper.id = "";
        var previewTemplate = previewWrapper.innerHTML;
        previewWrapper.remove();

        var myDropzone = new Dropzone(document.getElementById("form"), {
            url: "@Url.Action("CreateConteudoAnexoFiles")",
            paramName: "files",
            maxFiles: 10,
            maxFilesize: 100,
            timeout: 0,
            uploadMultiple: true,
            previewTemplate: previewTemplate,
            previewsContainer: "#previews",
            createImageThumbnails: false,
            clickable: ".fileinput-button",

            dictFileTooBig: "O tamanho deste ficheiro é demasiado grande! O tamanho máximo suportado é {{maxFilesize}}.",
            dictResponseError: "Ocorreu um erro ao submeter este ficheiro (Erro {{statusCode}})!",
            dictMaxFilesExceeded: "Só pode escolher no máximo 10 ficheiro",

            init: function() {
                let myDropzone = this;

                myDropzone.on("success", function (file) {
                    file.previewElement.querySelector(".remove").onclick = function () {
                        $.post("@Url.Action("DeleteConteudoAnexoFile")", { conteudoAnexoFileName: file.name }, function () {
                            if (file.isMockFile == true) {
                                myDropzone.options.maxFiles = myDropzone.options.maxFiles + 1;
                            }
                        });
                    }
                });

                $.get("@Url.Action("GetConteudoAnexoFiles")", function (data) {
                    data.forEach(function (file) {
                        let mockFile = { name: file.Name, size: file.Size, isMockFile: true };

                        myDropzone.files.push(mockFile);

                        myDropzone.emit("addedfile", mockFile);
                        myDropzone.emit("complete", mockFile);
                        myDropzone.emit("success", mockFile);

                        myDropzone.options.maxFiles = myDropzone.options.maxFiles - 1;
                    });
                });
            }
        });

    });
</script>