IntranetSite/ViewModels/DetailsConteudoPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using IntranetAssemblies.Models.Intranet;

namespace IntranetSite.ViewModels
{
    public class DetailsConteudoPartialViewModel
    {
        public Conteudo Conteudo { get; set; }
        public List<ConteudoAnexo> ConteudoAnexosList { get; set; }
        public List<string> Fotos { get; set; }
        public List<Link> Links { get; set; }
        public ConteudoPropriedade ConteudoEstado { get; set; }
        public ConteudoPropriedade ConteudoVisibilidade { get; set; }

        public Ficha_Curso Ficha_Curso_Dados { get; set; }

        public DetailsConteudoPartialViewModel()
        {
            Conteudo = new Conteudo();
            ConteudoAnexosList = new List<ConteudoAnexo>();
            ConteudoEstado = new ConteudoPropriedade();
            ConteudoVisibilidade = new ConteudoPropriedade();
            Fotos = new List<string>();
            Links = new List<Link>();
            Ficha_Curso_Dados = new Ficha_Curso();
        }
    }
}

IntranetSite/Controllers/ConteudosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Configuration;
using System.IO;

using IntranetSite.App_Start;
using IntranetSite.Clients;
using IntranetSite.Filters;
using IntranetSite.ViewModels;
using IntranetSite.Helpers;

using IntranetAssemblies.DataAcess;
using IntranetAssemblies.Models.Intranet;
using IntranetAssemblies.Models.QuoVadis.Cargos;
using IntranetAssemblies.Models;
using System.Threading.Tasks;

namespace IntranetSite.Controllers
{   
    public class ConteudosController : BaseController
    {
        private readonly IntranetService _intranetService = new IntranetService(ConfigurationManager.ConnectionStrings["intranetDBString"].ConnectionString);

        private readonly CargosClient _cargosClient = new CargosClient();

        //Lista os Conteudos pelas categorias definidas
        public ActionResult ListCategorias(int idCategoria)
        {
            ListCategoriasViewModel listCategoriasViewModel = new ListCategoriasViewModel();

            listCategoriasViewModel.Categoria = _intranetService.STP_Categorias_S(idCategoria);
            // Obtém, a partir dos respectivos ID's, todos os dados dos tipos de conteúdos, categoria e conteudos
            List<ConteudoCategoria> conteudosCategorias = new List<ConteudoCategoria>();
            List<Conteudo> conteudos = new List<Conteudo>();

            if (Autenticacao.IsLoggedIn())
            {
                if (Autenticacao.IsLoginAdmin(IntranetSession.Session.Username))
                {
                    // Obtém, a partir dos respectivos ID's, todos os dados dos tipos de conteúdos, categoria e conteudos
                    conteudosCategorias = _intranetService.STP_ConteudosCategorias_S_ByCategoria(idCategoria, 3,false);
                }
                else
                {
                    conteudos = _intranetService.STP_Conteudos_S_ByEstado(3, false);
                    // retornar os conteudos de acordo com as definições de visualiação de cada um
                    Parallel.ForEach(CheckPermission.CheckPermissionConteudos(conteudos), (conteudo) =>
                    {
                        ConteudoCategoria conteudoCategoria = _intranetService.STP_ConteudosCategorias_S_ByCategoriaAndConteudo(idCategoria, conteudo.Id);
                        if (conteudoCategoria.Id != 0)
                        {
                            conteudosCategorias.Add(conteudoCategoria);
                        }
                    });
                }
            }
            else
            {
                conteudosCategorias.AddRange(_intranetService.STP_ConteudosCategorias_S_ByCategoria(idCategoria, 3, true));
            }

            // retornar os conteudos de acordo com as definições de visualiação de cada um
            Parallel.ForEach(conteudosCategorias, (conteudoCategoria) =>
            {
                Conteudo conteudo = _intranetService.STP_Conteudos_S(conteudoCategoria.IdConteudo);

                listCategoriasViewModel.ConteudosList.Add(conteudo);
                listCategoriasViewModel.TiposConteudoList.Add(_cargosClient.GetTipoConteudo(conteudo.IdTipoConteudo));
            });

            return View(listCategoriasViewModel);
        }

        //Lista os conteudos pelo tipo de conteudo e orgao
        public ActionResult ListConteudos(int idTipoConteudo, int idOrgao, int? Ano)
        {
            ListConteudosViewModel listConteudosViewModel = new ListConteudosViewModel();

            // Obtém, a partir do respectivo ID, todos os dados do tipo de conteúdo e do órgão do conteúdo
            listConteudosViewModel.TipoConteudo = _cargosClient.GetTipoConteudo(idTipoConteudo);
            listConteudosViewModel.Orgao = _cargosClient.GetOrgao(idOrgao);
            listConteudosViewModel.AnosList = GetAnos();
            if(Ano != null)
            {
                listConteudosViewModel.Ano = Ano.ToString();
            }

            if (Autenticacao.IsLoggedIn())
            {
                if (Autenticacao.IsLoginAdmin(IntranetSession.Session.Username))
                {
                    if (Ano == null)
                    {
                        listConteudosViewModel.ConteudosList.AddRange(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, false).ToList());

                    }
                    else
                    {
                        listConteudosViewModel.ConteudosList.AddRange(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, false).Where(x => x.DataCriacao.Year == Ano).ToList());
                    }
                }
                else
                {
                    if (Ano == null)
                    {
                        listConteudosViewModel.ConteudosList.AddRange(CheckPermission.CheckPermissionConteudos(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, false).ToList()));

                    }
                    else
                    {
                        listConteudosViewModel.ConteudosList.AddRange(CheckPermission.CheckPermissionConteudos(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, false).Where(x => x.DataCriacao.Year == Ano).ToList()));

                    }
                }
            }
            else
            {
                if (Ano == null)
                {
                    //Publicos
                    listConteudosViewModel.ConteudosList.AddRange(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, true));

                }
                else
                {
                    listConteudosViewModel.ConteudosList.AddRange(_intranetService.STP_Conteudos_S_ByTipoConteudoAndOrgaoAndEstado(listConteudosViewModel.TipoConteudo.Id, listConteudosViewModel.Orgao.Id, 3, true).Where(x => x.DataCriacao.Year == Ano));

                }
            }

            return View(listConteudosViewModel);
        }

        protected List<ConteudoPropriedade> GetAnos()
        {
            List<ConteudoPropriedade> perfisAnosList = new List<ConteudoPropriedade>();
            List<Ano> anosList = new List<Ano>();
            anosList = _intranetService.STP_Conteudos_S_Anos();

            perfisAnosList.Add(new ConteudoPropriedade("Todos", ""));
            foreach (var item in anosList)
            {
                perfisAnosList.Add(new ConteudoPropriedade(item.Year.ToString(), item.Year.ToString()));
            }
            //perfisAnosList.Add(new ConteudoPropriedade("2020", "2020"));
            //perfisAnosList.Add(new ConteudoPropriedade("2021", "2021"));


            return perfisAnosList;
        }


        public ActionResult LoadDetailsConteudoPartials(int id, string intranetDetailsConteudoForm)
        {
            return RedirectToAction("LoadDetailsConteudoPartial", intranetDetailsConteudoForm, new { id = id });
        }

        [IntranetLoggedIn]
        public ActionResult CreateConteudos()
        {
            List<CreateEditConteudosViewModel> createConteudosViewModelsList = BuildCreateEditConteudosViewModelsList();

            return View(createConteudosViewModelsList);
        }

        [IntranetLoggedIn]
        public ActionResult EditConteudos()
        {
            List<CreateEditConteudosViewModel> editConteudosViewModelsList = BuildCreateEditConteudosViewModelsList();

            return View(editConteudosViewModelsList);
        }


        public ActionResult DetailsConteudos(int? idTipoConteudo)
        {
            List<CreateEditConteudosViewModel> detailsConteudosViewModelsList = BuildDetailsConteudosViewModelsList(idTipoConteudo);

            return View(detailsConteudosViewModelsList);
        }
        private List<CreateEditConteudosViewModel> BuildDetailsConteudosViewModelsList(int? idTipoConteudo)
        {
            List<Orgao> orgaoList_conteudos = new List<Orgao>();
            List<Orgao> orgaosList = new List<Orgao>();
            List<Conteudo> conteudosPermission = new List<Conteudo>();
            if (Autenticacao.IsLoggedIn())
            {
                if (Autenticacao.IsLoginAdmin(IntranetSession.Session.Username))
                {
                    if (idTipoConteudo == null)
                        orgaoList_conteudos = _intranetService.STP_Conteudos_S_OrgaoByEstado(3, false);
                    else
                        orgaoList_conteudos = _intranetService.STP_Conteudos_S_OrgaoByEstadoAndTipoConteudo(3, idTipoConteudo.Value, false);
                }
                else
                {

                    if (idTipoConteudo == null)
                        conteudosPermission = CheckPermission.CheckPermissionConteudos(_intranetService.STP_Conteudos_S_ByEstado(3, false).ToList());
                    else
                        conteudosPermission = CheckPermission.CheckPermissionConteudos(_intranetService.STP_Conteudos_S_ByTipoConteudoAndEstado(idTipoConteudo.Value, 3, false).ToList());

                    //Ordenar por IdOrgão e remover os duplicados
                    conteudosPermission = conteudosPermission
                                              .GroupBy(s => s.IdOrgao)
                                              .Select(grp => grp.FirstOrDefault())
                                              .OrderBy(s => s.IdOrgao)
                                              .ToList();

                    // retornar os conteudos de acordo com as definições de visualiação de cada um
                    Parallel.ForEach(conteudosPermission, (conteudo) =>
                    {

IntranetSite/Views/FormEventos/DetailsConteudoPartial.cshtml
@model IntranetSite.ViewModels.DetailsConteudoPartialViewModel

<style>
    .myVideo {
        padding: 10px;
    }

    iframe {
        margin: 0 auto;
        width: 560px;
        display: block;
        height: 325px;
    }

    video {
        margin: 0 auto;
        width: 560px;
        display: block;
        height: 325px;
    }

    img {
        margin: 0 auto;
        width: 90%;
        display: block;
        height: 250px;
    }
</style>

<div class="modal-header">
    <h2 class="modal-title" id="exampleModalLabel">@Model.Conteudo.Titulo</h2>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">

    <div class="row">
        <div class="col-md-12">
            <div>
                @if (Model.Fotos != null && Model.Fotos.Count() > 0)
                {

                    <div>
                        @*<h4>Foto</h4>
                        <hr />*@

                        <dl class="dl-horizontal">
                            <dd>
                                <div class="table-responsive">
                                    <div class="table table-striped">
                                        @foreach (var item in Model.Fotos)
                                        {
                                            <div class="col-md-12  text-center">
                                                <img src="@item" />
                                            </div>
                                            <br />
                                        }
                                    </div>
                                </div>
                            </dd>
                        </dl>
                    </div>
                }

            </div>
            <div>
                <dl class="row">
                    <dd class="col-md-12">
                        @Html.DisplayFor(model => model.Conteudo.Descricao)
                    </dd>
                </dl>
            </div>
            <div>
                <dl class="row">
                    <dt class="col-md-2">
                        @Html.DisplayNameFor(model => model.Conteudo.DataInicio)
                    </dt>

                    <dd class="col-md-4">
                        @Model.Conteudo.DataInicio.Value.ToShortDateString()
                    </dd>

                    <dt class="col-md-2">
                        @if (Model.Conteudo.HoraInicio != new TimeSpan())
                        {
                            @Html.DisplayNameFor(model => model.Conteudo.HoraInicio)
                        }
                    </dt>

                    <dd class="col-md-4">
                        @if (Model.Conteudo.HoraInicio != new TimeSpan())
                        {
                            @Html.DisplayFor(model => model.Conteudo.HoraInicio)
                        }
                    </dd>
                    <dt class="col-md-2">
                        @Html.DisplayNameFor(model => model.Conteudo.DataFim)
                    </dt>

                    <dd class="col-md-4">
                        @Model.Conteudo.DataFim.Value.ToShortDateString()
                    </dd>

                    <dt class="col-md-2">
                        @if (Model.Conteudo.HoraFim != new TimeSpan())
                        {
                            @Html.DisplayNameFor(model => model.Conteudo.HoraFim)
                        }
                    </dt>

                    <dd class="col-md-4">
                        @if (Model.Conteudo.HoraFim != new TimeSpan())
                        {
                            @Html.DisplayFor(model => model.Conteudo.HoraFim)
                        }
                    </dd>
                </dl>
                <dl class="row">
                    @if (Model.Conteudo.Link2 != null && Model.Conteudo.Link2 != "")
                    {
                        <dt class="col-md-3">

                            @Html.DisplayFor(model => model.Conteudo.LabelLink2)

                        </dt>


                        <dd class="col-md-3">
                            @*@Html.DisplayFor(model => model.Conteudo.Link2)*@
                            <a target="_blank" href="@Model.Conteudo.Link2">@Model.Conteudo.Link2</a>
                        </dd>
                    }
                    @if (Model.Conteudo.Link3 != null && Model.Conteudo.Link3 != "")
                    {
                        <dt class="col-md-3">
                            @Html.DisplayFor(model => model.Conteudo.LabelLink3)
                        </dt>

                        <dd class="col-md-3">
                            @*@Html.DisplayFor(model => model.Conteudo.Link3)*@
                            <a target="_blank" href="@Model.Conteudo.Link3">@Model.Conteudo.Link3</a>
                        </dd>
                    }


                            @if (Model.Conteudo.Link1 != null && Model.Conteudo.Link1 != "")
                            {
                                @*<dt class="col-md-3">
                        @Html.DisplayFor(model => model.Conteudo.LabelLink1)
                    </dt>*@

                                <dd class="col-md-12">

                                    @*@Html.DisplayFor(model => model.Conteudo.Link1)*@
                                    @*<a target="_blank" href="@Model.Conteudo.Link1">@Model.Conteudo.Link1</a>*@
                                    @*<pre name="https://www.w3schools.com/html/mov_bbb.mp4" class="myVideo"></pre>*@
                                    <pre name="@Model.Conteudo.Link1" class="myVideo"></pre>

                                </dd>
                            }

                </dl>

            </div>
            <div>
                @if (Model.ConteudoAnexosList != null && Model.ConteudoAnexosList.Count() > 0)
                {
                    <div>
                        <h4>Anexos</h4>
                        <hr />

                        <dl class="dl-horizontal">
                            <dd>
                                <div class="table-responsive">
                                    <div class="table table-striped" id="previews">
                                        @foreach (var item in Model.ConteudoAnexosList)
                                        {

                                            <div id="template" class="file-row">
                                                <div>
                                                    <p class="name" data-dz-name>@item.Anexo</p>
                                                </div>
                                                <div class="text-right">
                                                    <a data-dz-remove class="btn btn-secondary remove" href="@Url.Action("DownloadConteudoAnexoFile", new { conteudoDataCriacao = Model.Conteudo.DataCriacao, conteudoCodigoOrgao = Model.Conteudo.CodigoOrgao, conteudoAnexo = item.Anexo })" target="_blank">
                                                        <span class="fa fa-download"></span>

                                                    </a>
                                                </div>
                                            </div>

                                        }
                                    </div>
                                </div>
                            </dd>
                        </dl>
                    </div>
                }

                @{
                    Html.RenderPartial("FooterDetailsConteudoPartial", Model);
                }
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" data-dismiss="modal">
        <span class="fa fa-times"></span>
        Fechar
    </button>
</div>

<script>
    $('.myVideo').each(function () {
        function getId(url) {
            var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
            var match = url.match(regExp);

            if (match && match[2].length == 11) {
                return match[2];
            } else {
                return 'error';
            }
        }
        var videoId = $(this).attr("name");

        var myId = getId(videoId);
        if (myId != "error") {
            $('#videoSrc').html(myId);

            $(this).html('<iframe src="//www.youtube.com/embed/' + myId + '" frameborder="0" allowfullscreen></iframe>');
        }
        else {
            $(this).html('<video src="' + videoId + '" frameborder="0" allowfullscreen controls="true"></video>');
        }

    });
</script>

IntranetSite/Views/FormEventos/Index.cshtml
@model IntranetSite.ViewModels.ListConteudosViewModel

@{
    /**/

    ViewBag.Title = "Eventos";
}

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">
                <span class="fa fa-home"></span>
                
            </a>
        </li>
        <li class="breadcrumb-item active">
            @Model.TipoConteudo.Nome
        </li>
    </ol>
</nav>

@if (Model.ConteudosList.Count > 0)
{
    foreach (var item in Model.ConteudosList)
    {
        <div class="row">
            <div class="col-sm-4 col-xs-12">
                @if (item.LinkFoto != "")
                {
                    <img style="width:100%; height:100%" src="@item.LinkFoto" />
                }

            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <h3>
                        <a data-toggle="modal" data-target="#detailsConteudoModal" data-id="@item.Id" data-intranetdetailsconteudoform="@Model.TipoConteudo.IntranetDetailsConteudoForm" href="#detailsConteudoModal">
                            @item.Titulo
                        </a>
                    </h3>
                    <div style="color: #767676">
                        <span class="fa fa-clock-o"></span> @item.DataInicioPublicacao.Value.ToShortDateString()
                        <span>&nbsp;&nbsp;&nbsp; @item.NomeOrgao</span>
                    </div>
                </div>
                <br />
                <div class="text-overflow">
                    <p class="comment more">
                        @item.Descricao
                    </p>
                </div>
            </div>
        </div>
        <hr />
    }

    <div class="modal fade" id="detailsConteudoModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-xl" role="document" id="detailsConteudoModalDialog">
            <div id="detailsConteudoModalContent" class="modal-content">

            </div>

        </div>
        <div class="modal-dialog modal-dialog-centered text-center" role="document" id="loader" style="display:none">
            <div style="padding-left: 250px; padding-right: 250px; ">
                <div class="d-flex justify-content-center">
                    <div class="spinner-border" role="status" style="width: 4rem; height: 4rem;">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div>
        Não existem eventos para apresentar.
    </div>
}

<script>
    $(document).ready(function () {

        $("#detailsConteudoModal").on("hidden.bs.modal", function () {
            $('#detailsConteudoModalContent').empty();
        });

        $("#detailsConteudoModal").on("show.bs.modal", function (event) {
            var detailsConteudoModalButton = $(event.relatedTarget);
            var id = detailsConteudoModalButton.data("id");
            var intranetDetailsConteudoForm = detailsConteudoModalButton.data("intranetdetailsconteudoform");


            $('#detailsConteudoModalDialog').fadeOut();
            $('#loader').fadeIn();

            setTimeout(function () {
            $("#detailsConteudoModalContent").load("@Url.Action("LoadDetailsConteudoPartials","Conteudos")", { id: id, intranetDetailsConteudoForm: intranetDetailsConteudoForm }, function () {

                $('#detailsConteudoModalDialog').fadeIn();
                $('#loader').fadeOut();
            });
            }, 300);
        });

        var showChar = 200;
        var ellipsestext = "...";
        $('.more').each(function () {
            var content = $(this).html();

            if (content.length > showChar) {

                var c = content.substr(0, showChar);
                var h = content.substr(showChar - 1, content.length - showChar);

                var html = c + '<span class="moreellipses">' + ellipsestext + '&nbsp;</span>';

                $(this).html(html);
            }

        });
    });
</script>