IntranetSite/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Net;
using System.Linq;

using System.Configuration;
using System.Security.Cryptography;
using System.Threading;

using CaptchaMvc.HtmlHelpers;

using IntranetSite.App_Start;
using IntranetSite.Clients;
using IntranetSite.Filters;
using IntranetSite.Helpers;
using IntranetSite.ViewModels;

using IntranetAssemblies.DataAcess;
using IntranetAssemblies.Models;
using IntranetAssemblies.Models.Intranet;
using IntranetAssemblies.Models.QuoVadis.RCU;

namespace IntranetSite.Controllers
{
    public class SessionController : BaseController
    {
        private readonly IntranetService _intranetService = new IntranetService(ConfigurationManager.ConnectionStrings["intranetDBString"].ConnectionString);

        private readonly IUTADClient _iUTADClient = new IUTADClient();
        private readonly RCUClient _rcuClient = new RCUClient();

        [IntranetLoggedOff]
        public ActionResult Login()
        {
            return View();
        }

        // Esta é a função principal de autenticação
        // Verifica credenciais, obtém cargos e perfis do login e, com esses dados, verifica as autorizações que o login possui na aplicação
        // Adicionalmente regista o acesso do login na tabela de registo da base de dados do Intranet
        [IntranetUTAD]
        [IntranetLoggedOff]
        [HttpPost]
        public ActionResult Login(LoginViewModel loginViewModel)
        {
            // Primeiro valida os campos do nome de utilizador e da palavra-passe
            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Username) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Username", "Tem de introduzir um nome de utilizador válido!");
            }

            if(string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Password) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Password", "Tem de introduzir uma palavra-passe válida!");
            }

            if(ModelState.IsValid == true)
            {
                Login login = new Login();

                // Dependendo do valor da flag de simulação de autenticação presente no Web.config, usa diferentes mecanismos para autenticar o login
                if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD.Simul"]) == true)
                {
                    // Usa serviços Web de simulação para autenticar o login
                    login = AutenticacaoSimul.AutenticarLoginWSSimul(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                }
                else
                {
                    // Usa o serviço Web real de autenticação, que inclui o mecanismo de autenticação por impersonação
                    // Neste mecanismo, um administrador pode autenticar-se como se fosse um utilizador à sua escolha, e ver o que esse utilizador vê no Intranet
                    bool canAutenticarLoginWS = true;

                    if (loginViewModel.LoginCredenciais.Username.Contains(";") == true)
                    {
                        // Assumindo que o login introduzido se encontra na estrutura "administrador;login", separa o login em dois
                        string[] userAdminImpersonacao = loginViewModel.LoginCredenciais.Username.Split(';');

                        string adminImpersonacao = userAdminImpersonacao[0];
                        string userImpersonacao = userAdminImpersonacao[1];

                        if (string.IsNullOrEmpty(adminImpersonacao) == false && string.IsNullOrEmpty(userImpersonacao) == false)
                        {
                            canAutenticarLoginWS = Autenticacao.IsLoginAdmin(adminImpersonacao);
                        }
                        else
                        {
                            canAutenticarLoginWS = false;
                        }
                    }

                    if (canAutenticarLoginWS == true)
                    {
                        login = _iUTADClient.Auth(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }
                }

                // Se o login tiver sido autenticado com sucesso, procede para a função de carregamento do login
                if (login != null && login.IUPI != null && login.IUPI != new Guid())
                {
                    // -1 - Login não possui permissões
                    // 0 - Ocorreu um erro ao carregar o login
                    // 1 - Login carregado com sucesso
                    // 2 - Login carregado com sucesso (estudante)
                    int success = Autenticacao.LoadLogin(login);

                    switch (success)
                    {
                        case -1:
                            TempData["error"] = "Não possui permissões para aceder a esta aplicação!";

                            return View();

                        case 0:
                            TempData["error"] = "Ocorreu um erro ao carregar a informação pessoal!";

                            return View();

                        case 1:
                            if (Apresentacao.LoadLinguagem(Thread.CurrentThread.CurrentUICulture.Name) == true)
                            {
                                return RedirectToAction("Index", "Home");
                            }
                            else
                            {
                                TempData["error"] = "Ocorreu um erro ao carregar informação!";

                                return View();
                            }

                        case 2:
                            return RedirectToAction("LoadEstudantePerfil", new { iupi = login.IUPI });

                        default:
                            break;
                    }
                }
                else
                {
                    // Caso contrário, se o login não tiver sido autenticado com sucesso, significa que as credenciais introduzidas estão erradas
                    // Portanto apresenta uma mensagem de erro
                    TempData["error"] = "Credenciais inválidas! Por favor verifique as credenciais introduzidas e tente de novo.";
                }
            }
            else
            {
                // Caso o utilizador não tenha introduzido o nome de utilizador ou a palavra-passe, apresenta uma mensagem de erro
                TempData["error"] = "Tem de preencher todos os campos!";
            }

            return View();
        }

        [IntranetUTADLoginAdmin]
        [IntranetLoggedOff]
        public ActionResult LoginAdmin()
        {
            return View();
        }

        [IntranetUTADLoginAdmin]
        [IntranetLoggedOff]
        [HttpPost]
        public ActionResult LoginAdmin(LoginViewModel loginViewModel)
        {
            // Primeiro valida os campos do nome de utilizador e da palavra-passe
            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Username) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Username", "Tem de introduzir um nome de utilizador válido!");
            }

            if (string.IsNullOrEmpty(loginViewModel.LoginCredenciais.Password) == true)
            {
                ModelState.AddModelError("LoginCredenciais.Password", "Tem de introduzir uma palavra-passe válida!");
            }

            if (ModelState.IsValid == true)
            {
                Login login = new Login();

                // Primeiro verifica se as credenciais introduzidas correspondem a um administrador válido do Intranet
                bool isAdmin = false;

                if (loginViewModel.LoginCredenciais.Username.Contains(";") == true)
                {
                    // Assumindo que o login introduzido se encontra na estrutura "administrador;login", separa o login em dois
                    string[] userAdminImpersonacao = loginViewModel.LoginCredenciais.Username.Split(';');

                    string adminImpersonacao = userAdminImpersonacao[0];
                    string userImpersonacao = userAdminImpersonacao[1];

                    if (string.IsNullOrEmpty(adminImpersonacao) == false && string.IsNullOrEmpty(userImpersonacao) == false)
                    {
                        isAdmin = Autenticacao.IsLoginAdmin(adminImpersonacao);
                    }
                }
                else
                {
                    isAdmin = Autenticacao.IsLoginAdmin(loginViewModel.LoginCredenciais.Username);
                }

                if (isAdmin == true)
                {
                    // Dependendo do valor da flag de simulação de autenticação presente no Web.config, usa diferentes mecanismos para autenticar o login
                    if (Convert.ToBoolean(ConfigurationManager.AppSettings["Auth.UTAD.Simul"]) == true)
                    {
                        // Usa serviços Web de simulação para autenticar o login
                        login = AutenticacaoSimul.AutenticarLoginWSSimul(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }
                    else
                    {
                        // Usa o serviço Web real de autenticação, que inclui o mecanismo de autenticação por impersonação
                        // Neste mecanismo, um administrador pode autenticar-se como se fosse um utilizador à sua escolha, e ver o que esse utilizador vê no Intranet
                        login = _iUTADClient.Auth(loginViewModel.LoginCredenciais.Username, loginViewModel.LoginCredenciais.Password);
                    }

                    // Se o login tiver sido autenticado com sucesso, procede para a função de carregamento do login
                    if (login != null && login.IUPI != null && login.IUPI != new Guid())
                    {

IntranetSite/Views/Shared/FooterDetailsConteudoPartial.cshtml
@model IntranetSite.ViewModels.DetailsConteudoPartialViewModel

<hr />
<div class="small">
    <div class="row">
        <div class="col-md-10">
            @Html.DisplayNameFor(model => model.Conteudo.NomeTipoConteudo):
            @Model.Conteudo.NomeTipoConteudo
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-10">
            @Html.DisplayNameFor(model => model.Conteudo.NomeOrgao):
            @Model.Conteudo.NomeOrgao
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            @Html.DisplayNameFor(model => model.Conteudo.DataInicioPublicacao):
            @Model.Conteudo.DataInicioPublicacao.Value.ToShortDateString()
        </div>

        <div class="col-md-4">
            @Html.DisplayNameFor(model => model.Conteudo.DataFimPublicacao):

            @Model.Conteudo.DataFimPublicacao.Value.ToShortDateString()
        </div>
    </div>
</div>

IntranetSite/Views/Shared/_AlertsPartial.cshtml
@if (TempData["warning"] != null && string.IsNullOrEmpty(TempData["warning"].ToString()) == false)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-exclamation-triangle"></span>
            Aviso!
        </h4>
        @TempData["warning"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["success"] != null && string.IsNullOrEmpty(TempData["success"].ToString()) == false)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-check-circle"></span>
            Sucesso!
        </h4>
        @TempData["success"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["info"] != null && string.IsNullOrEmpty(TempData["info"].ToString()) == false)
{
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            <span class="fa fa-info-circle"></span>
            Informação
        </h4>
        @TempData["info"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["error"] != null && string.IsNullOrEmpty(TempData["error"].ToString()) == false)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert" aria-label="Fechar">
        <h4 class="alert-heading">
            <span class="fa fa-exclamation-circle"></span>
            Erro!
        </h4>
        @TempData["error"]

        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

IntranetSite/Views/Shared/_MenuLateralOrgaosPartial.cshtml
@model IntranetSite.ViewModels.ContactosOrgaosViewModel
@using IntranetSite.Helpers;
@using IntranetSite.ViewModels;

<style>

    .col-md-10 {
        padding-left: 5px;
        line-height: 20px;
        padding-bottom: 15px;
        padding-top: 15px;
    }
</style>

@foreach (var item in Model.Orgaos)
{
    if (item.Orgao.IdOrgaoParent == 0)
    {
        <a class="list-group-item list-group-item-action" data-toggle="collapse" href="@string.Concat("#orgaoCollapse", "Orgao")" name="@string.Concat("Orgaos", "MenuItem")" title="Orgãos da UTAD" aria-expanded="true">
            <span class="fa fa-search fa-fw"></span>
            Orgãos da UTAD
        </a>
        <div class="list-group collapse" id="@string.Concat("orgaoCollapse", "Orgao")">
            <div class="list-group-item list-group-item-action portalbase-sidebar-submenuitem">
                <span style="@string.Concat("padding-left:", Model.MenuItemPadding,"px;")">
                    <span class="fa fa-angle-double-right"></span>
                </span>
                <a class="portalbase-sidebar-submenuitem col-md-10" type="button" href="@Url.Action("Index", "Contactos", new { id = item.Orgao.Id })" title="@item.Orgao.Nome">
                    @item.Orgao.Codigo
                </a>
                <span class="float-right" type="button" data-toggle="collapse" data-target="@string.Concat("#orgaoCollapse", item.Orgao.Id)" aria-expanded="true" aria-controls="@string.Concat("#orgaoCollapse", item.Orgao.Id)">
                    <span name="0" class="fa fa-angle-double-down"></span>
                </span>
            </div>

            <div class="list-group collapse" id="@string.Concat("orgaoCollapse", item.Orgao.Id)">
                @{
                    Html.RenderPartial("_MenuLateralOrgaosPartial", OrgaoContacto.OrgaoContactoMenu(item.Orgao.Id));
                }
            </div>
        </div>
            }
            else
            {


        <div class="list-group-item list-group-item-action portalbase-sidebar-submenuitem">
            <span class="float-left" style="@string.Concat("padding-left:", Model.MenuItemPadding,"px;")">
                <span class="fa fa-angle-double-right"></span>
            </span>
            <a class="col-md-10" type="button" href="@Url.Action("Index", "Contactos", new { id = item.Orgao.Id })" title="@item.Orgao.Nome">
                @item.Orgao.Nome
            </a>
            @if (item.HasChild)
            {
            <span class="float-right" type="button" data-toggle="collapse" data-target="@string.Concat("#orgaoCollapse", item.Orgao.Id)" aria-expanded="true" aria-controls="@string.Concat("#orgaoCollapse", item.Orgao.Id)">
                <span name="0" class="fa fa-angle-double-down"></span>
            </span>
            }
        </div>
            <div class="list-group collapse" id="@string.Concat("orgaoCollapse", item.Orgao.Id)">
                @{
                    Html.RenderPartial("_MenuLateralOrgaosPartial", OrgaoContacto.OrgaoContactoMenu(item.Orgao.Id));
                }
            </div>
            }

            }

IntranetSite/Views/Shared/_MenuLateralPartial.cshtml
@model IEnumerable<IntranetAssemblies.Models.MenuItem>

@foreach (var item in Model)
{
    @Html.IntranetMenuItem(item);

    if (item.MenuItemChildList.Count > 0)
    {
        if (item.MenuItemChildListIsOpen == true)
        {
            <div class="list-group collapse show" id="collapseSidebar-@item.Id">
                @{
                    Html.RenderPartial("_MenuLateralPartial", item.MenuItemChildList);
                }
            </div>
        }
        else
        {
            <div class="list-group collapse" id="collapseSidebar-@item.Id">
                @{
                    Html.RenderPartial("_MenuLateralPartial", item.MenuItemChildList);
                }
            </div>
        }
    }
}

IntranetSite/Views/Shared/_MenuLateralSearchPessoasPartial.cshtml
@model IEnumerable<IntranetAssemblies.Models.QuoVadis.Pessoas.Pessoa>

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">
        <span class="fa fa-search"></span>
        pessoas.utad.pt - Procura
    </h5>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    @if (Model.Count() > 0)
    {
        <div class="list-group">
            @foreach (IntranetAssemblies.Models.QuoVadis.Pessoas.Pessoa item in Model)
            {
                <a href="@string.Concat("https://pessoas.utad.pt/detalhe.php?iupi=", item.Iupi)" class="list-group-item list-group-item-action" target="_blank">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@item.Nome</h5>
                    </div>

                    @foreach (IntranetAssemblies.Models.QuoVadis.Pessoas.PessoaPerfil itemPerfil in item.PessoaPerfisList)
                    {
                        if (itemPerfil.VisibilidadeCategoria == 2 || itemPerfil.VisibilidadeCategoria == 3)
                        {
                            <p class="mb-1">@itemPerfil.Categoria</p>
                        }

                        if (itemPerfil.VisibilidadeUo == 2 || itemPerfil.VisibilidadeUo == 3)
                        {
                            <p class="mb-1">@itemPerfil.Uo</p>
                        }
                    }
                </a>
            }
        </div>
    }
    else
    {
        <p>Não foram encontradas pessoas da UTAD!</p>
    }
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
</div>

IntranetSite/Views/Shared/_ProfilePartial.cshtml
@using IntranetSite.App_Start;

<div class="row">
    @if (string.IsNullOrEmpty(IntranetSession.Session.FotoHTMLSrc) == false)
    {
        <div class="col-md-2">
            <img class="portalbase-navbar-profile-foto" src="@IntranetSession.Session.FotoHTMLSrc" />
        </div>
    }
    else
    {
        <div class="col-md-2 portalbase-navbar-profile-foto-container">
            <img src="@Url.Content("~/Content/Images/iconPerfil.png")" />
        </div>
    }

        <div class="col-md-10">
            <p>
                @IntranetSession.Session.Nome
            </p>

            @if (Autenticacao.IsAdmin() == true)
            {
                <p>
                    (ADMINISTRADOR)
                </p>
            }

            @if (Autenticacao.IsEstudante() == true)
            {
                <p>
                    <label><b>Regime:</b></label>  @IntranetSession.Session.Regime
                </p>
                <p>
                    <label><b>Número:</b></label> @IntranetSession.Session.Username
                </p>
            }

            @if (Autenticacao.IsTemporario() == true)
            {
                <p>
                    (CONTA TEMPORÁRIA)
                </p>
            }

            @if (Autenticacao.IsTemporario() == true)
            {
                <a href=@Url.Action("EditCredenciaisTemporarias", "Session", new { username = IntranetSession.Session.Username })>
                    O Meu Perfil
                </a>

                <span>|</span>
            }
            else if (Autenticacao.IsEstudante() == false)
            {
                <a href="https://www.campus.utad.pt/omeuperfil/Perfil/AlterarDadosPessoais">
                    O Meu Perfil
                </a>

                <span>|</span>
            }

            <a href=@Url.Action("Logout", "Session")>
                <span class="fa fa-sign-out"></span>
                Terminar Sessão
            </a>
        </div>
</div>